### ISSUE TITLE
Hangs when distributing jobs

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#121]
EDIT: This is not just from /tmp. Maybe I am doing something wrong?

pbsmrtpipe just hangs. Here is the stack-trace (using #120):
```python
Process worker-task-pbsmrtpipe.tasks.bam2fasta-0:
Traceback (most recent call last):
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/engine.py", line 619, in run
    state, msg, run_time = self.runner_func(self.manifest_path)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/tools/runner.py", line 440, in run_task_manifest_on_cluster
    rcode, run_time = run_task_on_cluster(rt, path, output_dir, True)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/tools/runner.py", line 377, in run_task_on_cluster
    rcode, cstdout, cstderr, run_time = backticks("bash {q}".format(q=qshell))
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/engine.py", line 47, in backticks
    out = [l[:-1] for l in p.stdout.readlines()]
KeyboardInterrupt
Error executing function run_pipeline
Traceback (most recent call last):
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 878, in _wrapper
    state = func(*args, **kwargs)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 973, in run_pipeline
    workflow_level_opts, output_dir, service_uri)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 857, in exe_workflow
    _terminate_all_workers(workers.values(), shutdown_event)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 157, in _terminate_all_workers
    shutdown_event.set()
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/managers.py", line 1011, in set
    return self._callmethod('set')
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/opt/python-2.7.9/lib/python2.7/multiprocessing/connection.py", line 304, in SocketClient
    s.connect(address)
  File "/opt/python-2.7.9/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
```
That is the pbsmrtpipe subprocess. The parent process of course looks like this:
```python
Traceback (most recent call last):
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/fc_env/bin/pbtestkit-runner", line 9, in <module>
    load_entry_point('pbsmrtpipe==0.34.2', 'console_scripts', 'pbtestkit-runner')()
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/testkit/runner.py", line 232, in main
    return pacbio_args_runner(argv[1:], parser, _args_run_butler, log, setup_minimal_log)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbcommand/pbcommand/cli/core.py", line 143, in pacbio_args_runner
    return _pacbio_main_runner(alog, setup_log_func, args_runner_func, args)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbcommand/pbcommand/cli/core.py", line 76, in _pacbio_main_runner
    return_code = func(*args, **kwargs)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/testkit/runner.py", line 193, in _args_run_butler
    force_distribute=force_distribute, force_chunk=force_chunk)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/testkit/runner.py", line 153, in run_butler
    rcode, stdout, stderr, run_time = run_command_async(cmd, stdout_fh, stderr_fh)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/engine.py", line 245, in run_command_async
    time.sleep(1)
KeyboardInterrupt
```
Also, I'd love to see the output of line 45:
```python
 43     node_id = platform.node()
 44
 45     log.debug("Running on {s} with cmd '{c}'".format(s=node_id, c=cmd))
 46
 47     out = [l[:-1] for l in p.stdout.readlines()]
```
But unfortunately, I don't see it captured anywhere. I *do* see it for earlier `backticks` calls in the parent process (because of a change I made to enabled logging, for a future PR) but apparently not here in the sub-process.

I'll try running the underlying call directly...

**Comment by pb-cdunn** [comment]
Sub-sub-process was hung. What could help in this case would be if SIGINT could be sent to all qsub jobs. Now I'm trying to find out why it wasn't hanging for the local run...
