### ISSUE TITLE
How do I turn on maximum logging in testkit?

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#13]
For now, I need to see *all* logging from pbsmrtpipe/pbcommand. I already know what I did wrong, but I would like to be able to diagnose problems more quickly. Here is the stack-trace:

```python
[ERROR] 2015-08-20 17:14:35,959 Traceback (most recent call last):
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 868, in _wrapper
state = func(*args, **kwargs)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 938, in run_pipeline
bg = B.binding_strs_to_binding_graph(registered_tasks_d, workflow_bindings)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 466, in binding_strs_to_binding_graph
objs = [_to_objs_from_binding_str(registered_tasks, b_in, b_out) for b_in, b_out in {x for x in bindings}]
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 397, in _to_objs_from_binding_str
fi_file_type_instance = _get_output_index_or_raise(to_meta_task.task_id, to_meta_task.output_types, to_i)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 352, in _get_output_index_or_raise
return _get_index_or_raise("output", task_id_, output_types_, index_)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 346, in _get_index_or_raise
raise MalformedBindingStrError(emsg)
MalformedBindingStrError: MetaTask 'falcon_ns.tasks.task_falcon_config' Invalid index. Unable to get index 0 from max index -1 of output_types. []
```

I *like* the stack-trace. That's not the problem. But I would like even more to see the output of this line in bgraphy.py:

    365         log.info(("Binding parsed ", b_in, ti_id, ti_in, ti_index))

**Comment by natechols** [comment]
Did you try running with --log-level=DEBUG?

On Thu, Aug 20, 2015 at 10:50 AM, Christopher Dunn <notifications@github.com

**Comment by pb-cdunn** [comment]
That didn't help.

Besides, I already see INFO in the output. And for tasks, I think I've seen DEBUG. I think I need a different logging configuration.

**Comment by mpkocher** [comment]
Chris, I believe that error message is pretty good. If you systematically add a single binding and re-run the validate via make test-pipelines and iterate, it should be pretty clear where the error is. 

I'll add checking to make sure the tool contract has at least one output, which appears to be the fundamental problem?

**Comment by pb-cdunn** [comment]
To reiterate, I like the exception, and I already know the problem. I am asking how to get logging from pbsmrtpipe.

And no, it's not clear where the error is from.

> If you systematically add a single binding and re-run the validate via make test-pipelines and iterate, it should be pretty clear where the error is.

That is a luxury I may not always have.

**Comment by pb-cdunn** [comment]
I don't even have logging from my own task. Why is this question so difficult to answer?

Just tell me where logging is configured so I don't have to hunt for it. I'll modify it there.

**Comment by mpkocher** [comment]
Use --debug or set pbsmrtpipe.options.dev_mode = True in the preset.xml or pipeline.xml

This will
- enable debug level to stdout
- enable debug level to logs/master.log

**Comment by pb-cdunn** [comment]
I'll try these solutions when I have a chance.
