### ISSUE TITLE
Absence of outputs should not be an error.

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#16]
```python
Error executing function run_pipeline
Traceback (most recent call last):
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 868, in _wrapper
state = func(*args, **kwargs)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 961, in run_pipeline
workflow_level_opts, output_dir, service_uri)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 835, in exe_workflow
workers, shutdown_event, service_uri)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 535, in __exe_workflow
to_resources_func, to_resolve_files_func)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/opts_graph.py", line 528, in meta_task_to_task
cmd_str = meta_task.to_cmd(input_files, ofiles, resolved_values[SymbolTypes.RESOLVED_OPTS], resolved_values[SymbolTypes.NPROC], rfiles)
File "/home/UNIXHOME/cdunn/repo/pb/smrtanalysis-client/smrtanalysis/bioinformatics/ext/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/models.py", line 743, in to_cmd
output_dir = os.path.dirname(output_files[0])
IndexError: list index out of range
```
In models.py:
```python
738     def to_cmd(self, input_files, output_files, resolved_opts, nproc, resource_types, **kwargs):
739         """ This is all delegated to the RTC, hence the **kwargs
740         """
741         # get the job dir from the resolved value of the first output file,
742         # this should probably be accessed via ResourceType.JobDir
743         output_dir = os.path.dirname(output_files[0])
744         p = os.path.join(output_dir, RESOLVED_TOOL_CONTRACT_JSON)
745         return "{d} {m}".format(d=self.driver.driver_exe, m=p)
```

Here is my task:
```python
@registry('task_falcon_config', '0.0.0', [FileTypes.TXT], [], is_distributed=False)
def run_rtc(rtc):
    return run_falcon_config(rtc.task.input_files, rtc.task.output_files)
```

This is the 3rd example I've encountered in which pbsmrtpipe required non-empty input/output. (I've submitted pull-requests for the other 2.) In this case, as in the other 2, empty i/o helps me to integrate before implementation. This case is more important than the other 2, as it is at the Task level.

**Comment by mpkocher** [comment]
Every task must have a list one input and one output. This will be enforced at the pbcommand IO layer.

If you need a sentinel file, the use FileTypes.TXT.
