### ISSUE TITLE
chunking tests

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#39]
* testkit-data/dev_local_chunk does not seem to do any chunking. I'm looking for an example of the "Chunk-able task using dev_fofn chunk operator", but I don't see it.
* testkit-data/dev_local_fasta_chunk fails:

```python
[ERROR] 2015-09-02 20:01:46,622Z Task was not successful TaskResult(task_id='pbsmrtpipe.tasks.gather_fasta-1', state='failed', error_message='Failed with ex
it code 1', run_time_sec=1.04)
Task was not successful TaskResult(task_id='pbsmrtpipe.tasks.gather_fasta-1', state='failed', error_message='Failed with exit code 1', run_time_sec=1.04)
Traceback (most recent call last):
File "/opt/python-2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/opt/python-2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "pbsmrtpipe/pbsmrtpipe/tools_dev/gather_fasta.py", line 10, in <module>
from pbsmrtpipe.tools.gather import (gather_fasta,
File "pbsmrtpipe/pbsmrtpipe/tools/gather.py", line 14, in <module>
from pbcore.io import (SubreadSet, ContigSet, AlignmentSet, ConsensusReadSet,
ImportError: cannot import name ConsensusAlignmentSet
```

I'm at pbcore-1.2.2. Is that too recent?

**Comment by pb-cdunn** [comment]
Also, I see something odd:
```sh
$ ls
pbsmrtpipe.tasks.dev_filter_fasta-1
...
pbsmrtpipe.tasks.dev_filter_fasta-24
$ ls pbsmrtpipe.tasks.dev_scatter_filter_fasta-1/
scattered-fasta_0.fasta
...
scattered-fasta_23.fasta
```
In other words, the numbers are 1-based for the chunked tasks but filenames are 0-based when scattered. Is that expected? It might hinder debugging.

**Comment by pb-cdunn** [comment]
> In other words, the numbers are 1-based for the chunked tasks but filenames are 0-based when scattered. Is that expected? It might hinder debugging.
