### ISSUE TITLE
TaskChunkingError: Starting to chunk task-id ...

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#52]
The scatter task succeeds. Then, the chunked task does not even have its directory created. There is no command-line for it either. All I get is this error message:
```python
TaskChunkingError: Starting to chunk task-id falcon_ns.tasks.task_falcon1_run_daligner_jobs with chunk-group 9647db9e-beb0-4de2-8c94-45917b17dbf1
[ERROR] 2015-09-10 01:54:31,442Z Traceback (most recent call last):
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 875, in _wrapper
    state = func(*args, **kwargs)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 970, in run_pipeline
    workflow_level_opts, output_dir, service_uri)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 842, in exe_workflow
    workers, shutdown_event, service_uri)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 389, in __exe_workflow
    B.apply_chunk_operator(bg, global_registry.chunk_operators, global_registry.tasks, max_nchunks)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 1228, in apply_chunk_operator
    chunked_nodes = add_chunkable_task_nodes_to_bgraph(bg, tnode_, pipeline_chunks, chunk_operators, registered_tasks_d)
  File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 1127, in add_chunkable_task_nodes_to_bgraph
    raise TaskChunkingError("Starting to chunk task-id {i} with chunk-group {g}".format(i=task_type_to_scatter.task_id, g=chunk_group_id))
TaskChunkingError: Starting to chunk task-id falcon_ns.tasks.task_falcon1_run_daligner_jobs with chunk-group 9647db9e-beb0-4de2-8c94-45917b17dbf1

Shutting down.
[INFO] 2015-09-10 01:54:31,446Z Completed execution pbsmrtpipe v0.30.7. Workflow Failed in 47.22 sec (0.79 min)
Completed execution pbsmrtpipe v0.30.7. Workflow Failed in 47.22 sec (0.79 min)
```

**Comment by pb-cdunn** [comment]
And yes, `make test-sanity` passes. Any ideas?

**Comment by mpkocher** [comment]
It's reading in your pipeline chunks. If those are not well formed. This might be the source of your error. 

Can you post the output of scatter tasks (i.e., scatter.chunk.json).

**Comment by pb-cdunn** [comment]
```json
{
    "chunks": [],
    "_comment": "Chunks written at 2015-09-09 18:54:25.709535",
    "nchunks": 0,
    "_version": "0.1.0"
}
```
No chunks. Upstream error in this case.
