### ISSUE TITLE
Why does smrtpipe not wait for my jobs to finish ?

### ISSUE THREAD

**Issue by StefanReuscher** [PacificBiosciences/pbsmrtpipe#598]
Hi all,

I have installed smrtlink with the --smrt-tools-only option on my cluster. This cluster has a rather rare JMS, parallelnavi. I managed to configure it manually though.

I generated a preset.xml and put in a path to .tmpl files:

```
<?xml version="1.0" encoding="utf-8" ?>
<pipeline-preset-template>
    <options>
        <option id="pbsmrtpipe.options.debug_mode">
            <value>False</value>
        </option>
        <option id="pbsmrtpipe.options.max_nproc">
            <value>16</value>
        </option>
        <option id="pbsmrtpipe.options.tmp_dir">
            <value>/tmp</value>
        </option>
        <option id="pbsmrtpipe.options.chunk_mode">
            <value>True</value>
        </option>
        <option id="pbsmrtpipe.options.max_nchunks">
            <value>128</value>
        </option>
        <option id="pbsmrtpipe.options.distributed_mode">
            <value>True</value>
        </option>
        <option id="pbsmrtpipe.options.exit_on_failure">
            <value>False</value>
        </option>
        <option id="pbsmrtpipe.options.cluster_manager">
            <value>/home/usr9/z41809w/smrtlink/cluster_manager</value>
        </option>
        <option id="pbsmrtpipe.options.max_nworkers">
            <value>100</value>
        </option>
    </options>
</pipeline-preset-template>
```
start.tmpl looks like this:

```
pjsub --shell /bin/bash \
	--rsc-list "rscunit=cx,rscgrp=cx-debug,vnode=1,vnode-core=${NPROC},vnode-mem=32768,elapse=01:00:00" \
	-N ${JOB_ID} \
	-o ${STDOUT_FILE} -e ${STDERR_FILE} \
	${CMD} > info.catcher
```
> info.catcher catches some "Job submitted to cluster" message

stop.tmpl:
`pjdel ${JOB_ID}`

I ran a test pipeline and try to convert one of my older files from bax to bam:

```
pbsmrtpipe pipeline-id pbsmrtpipe.pipelines.sa3_hdfsubread_to_subread \
	--preset-xml test_preset.xml \
	-e eid_hdfsubread:/large/z41809w/IRGC110404_PacBio/O_longistaminata_IRGC110404__1-1/Analysis_Results/m160216_230124_42242_c100951042550000001823215806251665_s1_p0.1.bax.h5 \
	-o smrt_link_test

```

This fails with following error:

```
[INFO] 2017-12-11 09:07:28,580Z [status.pbsmrtpipe.driver __exe_workflow 267] successfully created job resources.
[INFO] 2017-12-11 09:07:28,580Z [status.pbsmrtpipe.driver __exe_workflow 269] starting to execute Distributed workflow with assigned job_id 680270
[INFO] 2017-12-11 09:07:28,581Z [status.pbsmrtpipe.driver __exe_workflow 270] system Linux cx07 nproc:24
[INFO] 2017-12-11 09:07:28,581Z [status.pbsmrtpipe.driver __exe_workflow 271] exe'ing workflow Cluster renderer <ClusterTemplateRender start:'pjsub --shell /bin/bash \
	--rsc-list "rscunit=cx,rscgrp=cx-debug,vnode=1,vnode-core=${NPROC},vnode-mem=32768,elapse=01:00:00" \
	-N ${JOB_ID} \
	-o ${STDOUT_FILE} -e ${STDERR_FILE} \
	${CMD} > info.catcher
' >
[INFO] 2017-12-11 09:07:28,582Z [status.pbsmrtpipe.driver __exe_workflow 272] FDQN of host cx07.nagoya-u
[INFO] 2017-12-11 09:07:28,582Z [status.pbsmrtpipe.driver __exe_workflow 274] Job Service URL is None. No updates will be sent
[INFO] 2017-12-11 09:07:28,582Z [status.pbsmrtpipe.driver __exe_workflow 277] Max number of Chunks  128 
[INFO] 2017-12-11 09:07:28,583Z [status.pbsmrtpipe.driver __exe_workflow 278] Max number of nproc   16
[INFO] 2017-12-11 09:07:28,583Z [status.pbsmrtpipe.driver __exe_workflow 279] Max number of workers 100
[INFO] 2017-12-11 09:07:28,583Z [status.pbsmrtpipe.driver __exe_workflow 280] tmp dir               /tmp
[INFO] 2017-12-11 09:07:28,584Z [pbsmrtpipe.graph.bgraph resolve_entry_point 894] EntryPointNode eid_hdfsubread PacBio.DataSet.HdfSubreadSet updating entry point successors [<EntryOutBindingFileNode PacBio.DataSet.HdfSubreadSet eid_hdfsubread>]
[INFO] 2017-12-11 09:07:28,585Z [pbsmrtpipe.graph.bgraph resolve_entry_point 894] EntryPointNode eid_hdfsubread PacBio.DataSet.HdfSubreadSet updating entry point successors [<EntryOutBindingFileNode PacBio.DataSet.HdfSubreadSet eid_hdfsubread>]
[INFO] 2017-12-11 09:07:28,586Z [status.__name__ label_chunkable_tasks 1168] Found chunkable task 'pbcoretools.tasks.h5_subreads_to_subread' assigning chunk-group fe9a32b1-7657-45a2-9c8a-31da1ad9d563
[INFO] 2017-12-11 09:07:28,586Z [status.pbsmrtpipe.driver __exe_workflow 296] validating binding graph
[INFO] 2017-12-11 09:07:28,587Z [status.pbsmrtpipe.driver __exe_workflow 299] successfully validated binding graph.
[INFO] 2017-12-11 09:07:28,590Z [status.pbsmrtpipe.driver __exe_workflow 307] pbsmrtpipe main process pid=13714 pgroupid=13714 ppid=29164
[INFO] 2017-12-11 09:07:29,394Z [status.pbsmrtpipe.driver __exe_workflow 699] Starting worker pbcoretools.tasks.h5_subreadset_scatter-1 (1 workers running, 1 total proc in use)
[INFO] 2017-12-11 09:07:29,399Z [pbsmrtpipe.engine run 633] Starting process:13898 TaskManifestWorker worker worker-task-pbcoretools.tasks.h5_subreadset_scatter-1 task-id:pbcoretools.tasks.h5_subreadset_scatter-1 task-uuid:b092be88-f1a4-48a2-96c7-016867bdc712
[INFO] 2017-12-11 09:07:29,473Z [pbsmrtpipe.tools.runner run_task_on_cluster 444] Cluster command return code 0 in 0.06 sec
[INFO] 2017-12-11 09:07:29,474Z [pbsmrtpipe.tools.runner run_task_on_cluster 448] 2017-12-11 18:07:29.474315 Completed running cluster command in 0.06 sec. Exit code 0 (task-type pbcoretools.tasks.h5_subreadset_scatter)
[INFO] 2017-12-11 09:07:29,478Z [pbsmrtpipe.tools.runner run_task_on_cluster 483] Writing task id pbcoretools.tasks.h5_subreadset_scatter task report to /home/usr9/z41809w/smrt_link_test/tasks/pbcoretools.tasks.h5_subreadset_scatter-1/task-report.json
[INFO] 2017-12-11 09:07:29,481Z [pbsmrtpipe.engine run 649] exiting Worker worker-task-pbcoretools.tasks.h5_subreadset_scatter-1 (pid 13898) task-id:pbcoretools.tasks.h5_subreadset_scatter-1 task-uuid:b092be88-f1a4-48a2-96c7-016867bdc712 TaskManifestWorker.run
**[INFO] 2017-12-11 09:07:29,663Z [status.pbsmrtpipe.driver __exe_workflow 566] Task was successful <TaskResult id:pbcoretools.tasks.h5_subreadset_scatter-1 state:successful runtime:0.06 sec uuid:b092be88-f1a4-48a2-96c7-016867bdc712 >
[WARNING] 2017-12-11 09:07:31,875Z [pbcommand.utils nfs_refresh 435] NFS refresh failed. unable to resolve /home/usr9/z41809w/smrt_link_test/tasks/pbcoretools.tasks.h5_subreadset_scatter-1/chunk.json**
[ERROR] 2017-12-11 09:07:31,876Z [status.pbsmrtpipe.driver __exe_workflow 755] Unexpected error Task TaskScatterBindingNode pbcoretools.tasks.h5_subreadset_scatter-1 Failed to find required OUTPUT file '/home/usr9/z41809w/smrt_link_test/tasks/pbcoretools.tasks.h5_subreadset_scatter-1/chunk.json'. Writing reports and shutting down
[ERROR] 2017-12-11 09:07:32,772Z [pbsmrtpipe.driver exe_workflow 996] Unexpected exception. shutting down.
Traceback (most recent call last):
  File "/home/usr9/z41809w/smrtlink/install/smrtlink-release_5.0.1.9585/bundles/smrttools/install/smrttools-release_5.0.1.9578/private/pacbio/pythonpkgs/pbsmrtpipe/lib/python2.7/site-packages/pbsmrtpipe/driver.py", line 989, in exe_workflow
    workers, shutdown_event, service_uri)
  File "/home/usr9/z41809w/smrtlink/install/smrtlink-release_5.0.1.9585/bundles/smrttools/install/smrttools-release_5.0.1.9578/private/pacbio/pythonpkgs/pbsmrtpipe/lib/python2.7/site-packages/pbsmrtpipe/driver.py", line 569, in __exe_workflow
    B.validate_outputs_and_update_task_to_success(bg, tnode_, result.run_time_sec, bg.node[tnode_]['task'].output_files)
  File "/home/usr9/z41809w/smrtlink/install/smrtlink-release_5.0.1.9585/bundles/smrttools/install/smrttools-release_5.0.1.9578/private/pacbio/pythonpkgs/pbsmrtpipe/lib/python2.7/site-packages/pbsmrtpipe/graph/bgraph.py", line 789, in validate_outputs_and_update_task_to_success
    raise TaskExecutionError(e_msg)
TaskExecutionError: Task TaskScatterBindingNode pbcoretools.tasks.h5_subreadset_scatter-1 Failed to find required OUTPUT file '/home/usr9/z41809w/smrt_link_test/tasks/pbcoretools.tasks.h5_subreadset_scatter-1/chunk.json'
[INFO] 2017-12-11 09:07:32,775Z [pbsmrtpipe.driver _terminate_all_workers 164] terminating 1 workers.
```

However the cluster job that creates the missing output runs successfully. If I restart the pipeline it will run, because the  missing output file is created. I assume smrtpipe thinks the job is already finished and proceeds with the next task. I get the same issue using a FALCON assembly pipeline and the ecoli example reads.

Why does the pipeline not wait on this job to finish ? What is the trigger that tells smrtpipe that a job is done ? Is it something in stdout or stderr? Wasnt there a sentinel file somewhere ?

I had the same issues with smrtanalysis and posted in the smrtanalysis repo maybe a year ago. At the time I solved this with the glorious --dryrun option to generate the scripts and submitted them manually in my own wrappers. Is there something equivalent in smrtpipe ?

Best Regards,

Stefan

**Comment by mpkocher** [comment]
Hi Stefan,

I'm not familiar with `parallelnavi`, however, my initial suggestion would be to make sure the cluster template command is indeed a blocking call (e.g., qsub -sync). [The docs](http://pbsmrtpipe.readthedocs.io/en/master/configuration_details.html) should be improved and clarify this requirement from cluster template interface.

You might have to write a wrapper/adapter to implement the blocking behavior for your specific scheduler if it's not natively supported.

Please see the the PBS wrapper in [qsw.py](https://github.com/PacificBiosciences/pbsmrtpipe/blob/master/extras/qsw.py). This might be a useful starting point for hacking. 

Best,

-Michael

**Comment by StefanReuscher** [comment]
Michael,

That was really great advice. I implemented blocking behaviour into parallelnavi:

```
pjsub -z jid --shell /bin/bash \
	--rsc-list "rscunit=cx,rscgrp=cx-debug,vnode=1,vnode-core=${NPROC},vnode-mem=32768,elapse=01:00:00" \
	-N ${JOB_ID} \
	-o ${STDOUT_FILE} -e ${STDERR_FILE} \
	${CMD} | xargs pjwait
```

-z jid makes pjsub emit the jobid to stdout, then I pipe the jid into pjwait to wait on the job to finish. Thank you for solving this long-standing mystery for me.
What will happen if there are more than 1 parallel jobs. Will the pipe submit multiple jobs and wait for all to finish ? 

Gruß,

Stefan
