### ISSUE TITLE
Job fail

### ISSUE THREAD

**Issue by mforde84** [PacificBiosciences/pbsmrtpipe#606]
Hey guys,

I'm receiving the following error:

```
[smrtanalysis@student44 000017]$ cat pbscala-job.stderr
Job 17 Failed to execute or import Pbsmrtpipe job /opt/pacbio/smrtlink/userdata/jobs_root/000/000017 failed with exit code 1. Task pbcoretools.tasks.filterdataset-0 Unhandled exception in Worker worker-task-pbcoretools.tasks.filterdataset-0 running task pbcoretools.tasks.filterdataset-0. Exception 
java.lang.Exception: Pbsmrtpipe job /opt/pacbio/smrtlink/userdata/jobs_root/000/000017 failed with exit code 1. Task pbcoretools.tasks.filterdataset-0 Unhandled exception in Worker worker-task-pbcoretools.tasks.filterdataset-0 running task pbcoretools.tasks.filterdataset-0. Exception 
	at com.pacbio.secondary.smrtlink.jobtypes.package$ServiceCoreJobModel.runTry(package.scala:106)
	at com.pacbio.secondary.smrtlink.jobtypes.package$ServiceCoreJobModel.runTry$(package.scala:98)
	at com.pacbio.secondary.smrtlink.jobtypes.package$ServiceCoreJob.runTry(package.scala:360)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.runJobAndImport(ServiceJobRunner.scala:166)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.$anonfun$runner$3(ServiceJobRunner.scala:259)
	at scala.util.Success.flatMap(Try.scala:247)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.$anonfun$runner$2(ServiceJobRunner.scala:251)
	at scala.util.Success.flatMap(Try.scala:247)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.runner(ServiceJobRunner.scala:250)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.runCore(ServiceJobRunner.scala:360)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.runCoreJob$1(ServiceJobRunner.scala:390)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.$anonfun$run$2(ServiceJobRunner.scala:395)
	at scala.util.Success.transform(Try.scala:247)
	at com.pacbio.secondary.smrtlink.jobtypes.ServiceJobRunner.run(ServiceJobRunner.scala:396)
	at com.pacbio.secondary.smrtlink.actors.EngineCoreJobWorkerActor$$anonfun$receive$1.applyOrElse(EngineCoreJobWorkerActor.scala:46)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at com.pacbio.secondary.smrtlink.actors.EngineCoreJobWorkerActor.aroundReceive(EngineCoreJobWorkerActor.scala:18)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mforde84** [comment]
Appears that it's having difficulty finding a file:

```
[INFO] 2019-02-14 16:28:38,509Z [pbsmrtpipe.tools.runner run_task_on_cluster 435] Job submission command: /opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/admin/bin/runjmscmd \
    --start \
    --jobname job.2503259pbcoretools.tasks.filterdataset \
    --stdoutfile "/opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/cluster.stdout" \
    --stderrfile "/opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/cluster.stderr" \
    --nproc "1" \
    --cmd "/opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/run.sh"

[INFO] 2019-02-14 16:28:38,592Z [pbsmrtpipe.tools.runner run_task_on_cluster 456] Underlying JMS job submission command: LOGNAME='smrtanalysis' PATH='/bin:/usr/bin:/bin' TERM='xterm-256color' USER='smrtanalysis' /bin/salloc --job-name=job.2503259pbcoretools.tasks.filterdataset --nodes=1 --cpus-per-task=1 /bin/srun --cpus-per-task=1 --ntasks=1 -o /opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/cluster.stdout -e /opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/cluster.stderr /bin/bash -c /opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/run.sh
[INFO] 2019-02-14 16:39:10,008Z [pbsmrtpipe.tools.runner run_task_on_cluster 461] Cluster command return code 0 in 631.41 sec
[INFO] 2019-02-14 16:39:10,009Z [pbsmrtpipe.tools.runner run_task_on_cluster 465] 2019-02-14 10:39:10.009235 Completed running cluster command in 631.41 sec. Exit code 0 (task-type pbcoretools.tasks.filterdataset)
[ERROR] 2019-02-14 16:39:10,009Z [pbsmrtpipe.engine run 646] Unhandled exception in Worker worker-task-pbcoretools.tasks.filterdataset-0 running task pbcoretools.tasks.filterdataset-0. Exception 
Traceback (most recent call last):
  File "/opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/bundles/smrttools/install/smrttools-release_6.0.0.47835/private/thirdparty/python/python_2.7.9/site-packages/pbsmrtpipe/engine.py", line 638, in run
    state, msg, run_time = self.runner_func(self.manifest_path)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/bundles/smrttools/install/smrttools-release_6.0.0.47835/private/thirdparty/python/python_2.7.9/site-packages/pbsmrtpipe/tools/runner.py", line 539, in run_task_manifest_on_cluster
    rcode, err_msg, run_time = run_task_on_cluster(rt, path, output_dir, True)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/bundles/smrttools/install/smrttools-release_6.0.0.47835/private/thirdparty/python/python_2.7.9/site-packages/pbsmrtpipe/tools/runner.py", line 498, in run_task_on_cluster
    r = update_task_report(task_report_path, run_time)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/bundles/smrttools/install/smrttools-release_6.0.0.47835/private/thirdparty/python/python_2.7.9/site-packages/pbsmrtpipe/tools/runner.py", line 101, in update_task_report
    rpt = load_report_from_json(report_path)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_6.0.0.47841/bundles/smrttools/install/smrttools-release_6.0.0.47835/private/thirdparty/python/python_2.7.9/site-packages/pbcommand/pb_io/report.py", line 134, in load_report_from_json
    with open(json_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '/opt/pacbio/smrtlink/userdata/jobs_root/000/000017/tasks/pbcoretools.tasks.filterdataset-0/task-report.json'
[INFO] 2019-02-14 16:39:10,012Z [pbsmrtpipe.engine run 649] exiting Worker worker-task-pbcoretools.tasks.filterdataset-0 (pid 49445) task-id:pbcoretools.tasks.filterdataset-0 task-uuid:ed36edfc-115e-45ca-9b6a-f42a883ecdf6 TaskManifestWorker.run
[ERROR] 2019-02-14 16:39:10,861Z [status.pbsmrtpipe.driver _log_task_failure_and_call_services 492] Task pbcoretools.tasks.filterdataset-0 Unhandled exception in Worker worker-task-pbcoretools.tasks.filterdataset-0 running task pbcoretools.tasks.filterdataset-0. Exception 
[ERROR] 2019-02-14 16:39:10,862Z [pbsmrtpipe.driver _log_task_failure_and_call_services 493] Task pbcoretools.tasks.filterdataset-0 Unhandled exception in Worker worker-task-pbcoretools.tasks.filterdataset-0 running task pbcoretools.tasks.filterdataset-0. Exception 
[INFO] 2019-02-14 16:39:10,909Z [pbsmrtpipe.driver __exe_workflow 660] Workflow status 2/16 completed/total tasks
[INFO] 2019-02-14 16:39:10,909Z [status.pbsmrtpipe.driver __exe_workflow 661] Workflow status 2/16 completed/total tasks
[ERROR] 2019-02-14 16:39:10,929Z [pbsmrtpipe.driver __exe_workflow 672] job has failed. breaking out.
[ERROR] 2019-02-14 16:39:11,698Z [pbsmrtpipe.driver _write_final_results_message 847]  Failed to run workflow.
[INFO] 2019-02-14 16:39:11,699Z [status.pbsmrtpipe.driver _wrapper 1122] Completed execution pbsmrtpipe v0.66.0. Workflow Failed in 635.06 sec (10.58 min) with exit code 1
[INFO] 2019-02-14 16:39:11,699Z [pbsmrtpipe.driver _wrapper 1123] Completed execution pbsmrtpipe v0.66.0. Workflow Failed in 635.06 sec (10.58 min) with exit code 1
[INFO] 2019-02-14 16:39:11,700Z [root main_runner 130] exiting with return code 1 in 635.18 sec.

```

**Comment by natechols** [comment]
This happens occasionally due to NFS latency.  Is it reproducible?

**Comment by mforde84** [comment]
Yea. Some of the jobs get through, and show as running in the slurm queue.

**Comment by mforde84** [comment]
also /opt is being hosted under local drive, so it shouldn't be touching nfs.

**Comment by natechols** [comment]
Is the Slurm queue running entirely on the head node then?

**Comment by mforde84** [comment]
you know that's probably the issue. i just inherited this system. let me dig through for a second. i tested an interactive srun --pty bash on the node in question and it just hangs. while the squeue on headnodes shows it as running

**Comment by mforde84** [comment]
Ok that resolved the issue.

If you wouldn't mind offering your suggestion on something else it would be helpful.

So we are using a head node to masquerade forward to a compute node hosting the services \

https://headnode:13337 -> https://smrt_node:8243/sl

Port are open on smrt_node an the forwarding is ok from head node, however the landing page doesn't load appropriately, I just get hung on "Loading...". I assume I also have to forward additional traffic to the host, is there a preferred way to do this or can you offer a suggestion?

Thanks, M

**Comment by natechols** [comment]
This isn't something I've ever tried and it may be officially unsupported but I suspect there are ways to make it work.  Open the Chrome developer tools and look at the Network tab when you try to load the page - this should give you some insight into what queries are being blocked.
