### ISSUE TITLE
bam2fasta error 

### ISSUE THREAD

**Issue by npbhavya** [PacificBiosciences/pbsmrtpipe#607]
I am running into this error 

Task pbcoretools.tasks.bam2fasta-3 Failed task pbcoretools.tasks.bam2fasta exit code 2 in 1.51 sec (See file '/home/ncgas_admin/output2/tasks/pbcoretools.tasks.bam2fasta-3/stderr'.)
Extracted from stderr
/bin/bash: bam2fasta: command not found
bam2fasta exited with code 127
Traceback (most recent call last):
  File "/opt/pbsmrtpipe/src/pbcommand/pbcommand/cli/core.py", line 139, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/opt/pbsmrtpipe/src/pbcoretools/pbcoretools/tasks/bam2fasta.py", line 56, in run_rtc
    tmp_dir=rtc.task.tmpdir_resources[0].path)
  File "/opt/pbsmrtpipe/src/pbcoretools/pbcoretools/bam2fastx.py", line 137, in _run_bam_to_fastx
    p=program_name, c=result.exit_code)
AssertionError: bam2fasta exited with code 127

Bam2fasta.py is in the /opt/pbsmrtpipe/src/pbcoretools/pbcoretools/bam2fastx.py, and I added this to my path but the workflow still runs into the error that the command is not found

**Comment by npbhavya** [comment]
Not sure if this is the best fix, but I ended up using conda install to install the bam2fastx script, set the paths to this script and then run the pbsmrtpipe. That seems to do the trick for now.
