### ISSUE TITLE
Error in pb_sv_clr

### ISSUE THREAD

**Issue by peeyushsahu** [PacificBiosciences/pbsmrtpipe#609]
I am migrating to smrtlink 9.0 and facing an issue during structural analysis with pb_sv_clr. It is throwing error when reading the reference data.
When I give it a reference set.XML error is :

````/bin/bash: Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/binwrap/../../../../thirdparty/ncurses/ncurses_6.1/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/binwrap/../../../../thirdparty/ncurses/ncurses_6.1/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/binwrap/../../../../thirdparty/ncurses/ncurses_6.1/lib/libtinfo.so.5: no version information available (required by /bin/bash)
Companion FASTA index (.fai) file malformatted! Use 'samtools faidx' to generate FASTA index
Traceback (most recent call last):
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcommand/cli/core.py", line 175, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcoretools/dataset.py", line 64, in run
    return args.func(args)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcoretools/DataSetEntryPoints.py", line 92, in createXml
    referenceFastaFname=args.reference_fasta_fname)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 140, in openDataFile
    return dsType(*origFiles, **kwargs)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2713, in __init__
    super().__init__(*files, **kwargs)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2086, in __init__
    super().__init__(*files, **kwargs)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 552, in __init__
    self.updateCounts()
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2631, in updateCounts
    self.assertIndexed()
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2483, in assertIndexed
    self._assertIndexed(IndexedBamReader)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2040, in _assertIndexed
    self._openFiles()
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/dataset/DataSetIO.py", line 2161, in _openFiles
    sharedRefs[refFile] = IndexedFastaReader(refFile)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/FastaIO.py", line 419, in __init__
    self.fai = loadFastaIndex(self.faiFilename, self.view)
  File "Xxx/smrtlink_9.0/install/smrtlink-release_9.0.0.92188/bundles/smrttools/install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/FastaIO.py", line 269, in loadFastaIndex
    raise IOError("Companion FASTA index (.fai) file malformatted! "
OSError: Companion FASTA index (.fai) file malformatted! Use 'samtools faidx' to generate FASTA index````

XML file created with:
`dataset create --type ReferenceSet \
referenceset.xml \
genome.fa \
--generateIndices`

File looks like:
`<?xml version="1.0" encoding="UTF-8"?>
<pbds:ReferenceSet CreatedAt="2021-01-07T16:14:03" MetaType="PacBio.DataSet.ReferenceSet" Name="pacbio_dataset_referenceset-210107_151403439" Tags="" TimeStampedName="pacbio_dataset_referenceset-210107_151403439" UniqueId="53528ae6-fac5-ec74-d9ff-a7c9a01e2a36" Version="3.0.1" xmlns:pbbase="http://pacificbiosciences.com/PacBioBaseDataModel.xsd" xmlns:pbds="http://pacificbiosciences.com/PacBioDatasets.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pacificbiosciences.com/PacBioDataModel.xsd">
	<pbbase:ExternalResources>
		<pbbase:ExternalResource MetaType="PacBio.ContigFile.ContigFastaFile" ResourceId="/XXX/genome.fa" TimeStampedName="pacbio_contigfile_contigfastafile-210107_151403438" UniqueId="676a9b69-63e3-47ca-ae14-c66e8d618aaa">
			<pbbase:FileIndices>
				<pbbase:FileIndex MetaType="PacBio.Index.SamIndex" ResourceId="/XXX/genome.fa.fai" TimeStampedName="pacbio_index_samindex-210107_151403570" UniqueId="4567ffe2-f208-4629-8945-8ab4b90b4a32"/>
			</pbbase:FileIndices>
		</pbbase:ExternalResource>
	</pbbase:ExternalResources>
	<pbds:DataSetMetadata>
		<pbds:TotalLength>0</pbds:TotalLength>
		<pbds:NumRecords>0</pbds:NumRecords>
		<pbds:Organism>unknown</pbds:Organism>
		<pbds:Ploidy>haploid</pbds:Ploidy>
	</pbds:DataSetMetadata>
</pbds:ReferenceSet>
`

This is the command I am running:
`pbcromwell run pb_sv_clr \
-e eid_ref_dataset:referenceset.xml \
-e eid_subread:XXXX.subreadset.xml \
-n 12 \
--output-dir XXXX/ \
--overwrite`

**Comment by natechols** [comment]
Please don't use the pbsmrtpipe repo to report unrelated problems - this project is obsolete and unmaintained and we don't regularly monitor issues here.  You need to regenerate the .fai file by running `samtools faidx genome.fa` again.

**Comment by peeyushsahu** [comment]
Thank you for your reply. Can you tell me where should file bug report in future? 

I found a bug in function **loadFastaIndex()**
"install/smrttools-release_9.0.0.92188/private/thirdparty/python3/python3_3.7.3/site-packages/pbcore/io/FastaIO.py" 

It does not read the error properly if in .fasta file there is empty line between end of one sequence and beginning of new. The error msg is not specific enough.
